# Generated by Django 4.1.4 on 2023-01-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
